```toml
[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm exec turbo build --filter=api"]

[start]
cmd = "pnpm --filter=api start"
```
